### ISSUE TITLE
Mypage 조회 및 수정 api

### ISSUE THREAD

**Issue by waterricecake** [waterricecake/tdm-backend#13]
## Summary
MyPage 조회 및 수정 api 구현
## Tasks
 - [x] 조회 api 구현
 - [x] 학교 정보 수정 api
 - [x] 관심사 정보 수정 api
