### ISSUE TITLE
test 환경 구축

### ISSUE THREAD

**Issue by waterricecake** [waterricecake/tdm-backend#4]
## summary

전체적인 테스트 구조를 구축하고 api 문서화를

## tasks
- [x] 추상화된 integration test 구현
- [x] 추상화된 service test 구현
- [x] 추상화된 repository 테스트 구현
- [ ] Swagger 환경 구축
- [x] 추상화된 Controller 테스트 구현
